/* Generated By:JavaCC: Do not edit this line. CdbParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface CdbParserTreeConstants
{
  public int JJTSCRIPT = 0;
  public int JJTVOID = 1;
  public int JJTCOMPOUNDSTATEMENT = 2;
  public int JJTWHILELOOP = 3;
  public int JJTFORLOOP = 4;
  public int JJTDOLOOP = 5;
  public int JJTIFSTATEMENT = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTEE = 8;
  public int JJTNE = 9;
  public int JJTLT = 10;
  public int JJTLE = 11;
  public int JJTGT = 12;
  public int JJTGE = 13;
  public int JJTADD = 14;
  public int JJTSUBTRACT = 15;
  public int JJTMULTIPLY = 16;
  public int JJTDIVIDE = 17;
  public int JJTVARIABLE = 18;
  public int JJTINTEGERCONSTANT = 19;
  public int JJTREALCONSTANT = 20;


  public String[] jjtNodeName = {
    "script",
    "void",
    "compoundStatement",
    "whileLoop",
    "forLoop",
    "doLoop",
    "ifStatement",
    "assignment",
    "EE",
    "NE",
    "LT",
    "LE",
    "GT",
    "GE",
    "add",
    "subtract",
    "multiply",
    "divide",
    "variable",
    "integerConstant",
    "realConstant",
  };
}
/* JavaCC - OriginalChecksum=0ef8a3031c6426d5fdc2a6056f866de1 (do not edit this line) */
